plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly("org.projectlombok:lombok:1.18.42")
	annotationProcessor("org.projectlombok:lombok:1.18.42")

    testImplementation 'junit:junit:4.13'
}

group = 'com.github.martin-der'

gradlePlugin {
    plugins {
        shellPackage {
            id = 'shell-package'
            implementationClass = 'net.tetrakoopa.gradle.plugin.shell.ShellPackagePlugin'
        }
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.FAIL
    archiveBaseName = "shell-package-plugin"
}

sourceSets {
    main {
        resources {
            srcDirs "tool"
        }
    }
}


def functionalTest = sourceSets.create('functionalTest')
gradlePlugin.testSourceSets(functionalTest)

configurations[functionalTest.implementationConfigurationName].extendsFrom(configurations.testImplementation)
// configurations[functionalTest.implementationConfigurationName].dependencies({
    // compileOnly("org.projectlombok:lombok:1.18.42")
	// annotationProcessor("org.projectlombok:lombok:1.18.42")
// })
configurations[functionalTest.compileOnlyConfigurationName].extendsFrom(configurations.compileOnly)
configurations[functionalTest.annotationProcessorConfigurationName].extendsFrom(configurations.annotationProcessor)

def functionalTestTask = tasks.register('functionalTest', Test) {
    testClassesDirs = functionalTest.output.classesDirs
    classpath = configurations[functionalTest.runtimeClasspathConfigurationName] + functionalTest.output
}
tasks.check.configure {
    dependsOn(functionalTestTask)
}

// Fix : Cleanup by renaming gralde files after tests are done so VScode doesn't get confused when scaning the project
tasks.register('cleanFunctionalTestBuildFiles') {
    doLast {
        fileTree("$buildDir/functionalTest/packaage").matching {
            include '**/build.gradle'
            include '**/settings.gradle'
        }.each { f ->
            f.renameTo(new File(f.parentFile, 'not-a-'+f.name))
        }
    }
}
tasks.named('functionalTest') {
    finalizedBy('cleanFunctionalTestBuildFiles')
}


